require_relative '../../core_ext'
require 'chef/knife'

class LisausaKnifePlugins::SetupSsh < ::Chef::Knife
  banner 'knife setup ssh'

  deps do
    require 'chef/shef/ext'
  end

  # This method will be executed when you run this knife command.
  def run
    Shef::Extensions.extend_context_object(self)
    config = []
    nodes.all do |n|
      next if /vagrant/.match(n.name)
      name = n.name
      name << '.lisausa.net' unless /\.lisausa.net\Z/.match(n.name)

      config << <<-END.strip_heredoc
        Host #{name}
          HostName #{n[:cloud][:public_hostname]}
      END
    end

    ui.msg "Copy and paste the following into your ~/.ssh/config file:"
    puts "## This is generated by `knife setup ssh`:\n\n#{config.join("\n")}"
  end

end
