require_relative '../../core_ext'
require 'chef/knife'

module LisaUSA
  class SetupSsh < Chef::Knife

    deps do
      require 'chef/shef/ext'
    end

    # This method will be executed when you run this knife command.
    def run
      Shef::Extensions.extend_context_object(self)
      config = []
      nodes.all do |n|
        next if /vagrant/.match(n.name)
        name = n.name
        name << '.lisausa.net' unless /\.lisausa.net\Z/.match(n.name)

        config << <<-END.strip_heredoc
          Host #{name}
            HostName #{n[:ipaddress]}
        END
      end

      puts <<-MESSAGE.strip_heredoc
        Copy and paste the following into your ~/.ssh/config file:

        ## This is generated by `knife ssh config`:

      MESSAGE
      puts config
    end

  end
end